name: MirrorSC-Actions
on:
  push:
    branches: [sc]

env:
  TZ: America/Recife
      
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 525600

    steps:
      - name: Checkouts
        uses: actions/checkout@main
      - uses: rokibhasansagar/slimhub_actions@main
      
      - name: Reclaiming disk space on / by disabling swap partition
        run: |
          sudo swapoff -av
          sudo rm -f /swapfile

      - name: Set Git Configs & Secrets
        run: |
          git config --global user.email "${{ secrets.GH_EMAIL }}"
          git config --global user.name "${{ secrets.GH_NAME }}" 
          git config --global pull.rebase false
          git config --global credential.helper store
          echo "https://FabriSC:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials

      - name: cloning repo 
        continue-on-error: true
        run: |
          git clone ${{ secrets.RP_MIRROR }} MirrorSC
          git clone https://github.com/${{ secrets.GH_NAME }}/MirrorSC-Actions.git SC
   
      - name: install docker and configuration
        continue-on-error: true
        run: |
          curl -fsSL https://get.docker.com -o get-docker.sh && sudo sh get-docker.sh
       
      - name: Running Bot
        timeout-minutes: 360
        continue-on-error: true
        run: |
          cd MirrorSC
          docker build . --rm --force-rm --compress --no-cache=true --pull --file Dockerfile -t mirror-bot
          docker run --privileged --rm -i mirror-bot
           
      - name: Loop workflow
        continue-on-error: true
        run: |
          cd SC
          git commit --allow-empty -m "[LOOP] Re-run MirrorSC workflow"
          git push -f
