name: MirrorSC-Actions
on:
  push:
    branches: [sc]

env:
  TZ: America/Recife
      
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 525600

    steps:
      - name: Checkeando y Limpiando vps
        uses: actions/checkout@main
      - uses: rokibhasansagar/slimhub_actions@main

      - name: Configurando Instancia
        run: |
          git config --global user.email "${{ secrets.GH_EMAIL }}"
          git config --global user.name "${{ secrets.GH_NAME }}" 
          git config --global pull.rebase false
          git config --global credential.helper store
          echo "https://${{ secrets.GH_NAME }}:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials

      - name: Clonando Repositorio
        continue-on-error: true
        run: |
          git clone https://github.com/FabriSC/fabriscmirror.git MirrorSC
          git clone https://github.com/FabriSC/fabriscmirror.git SC
          
      - name: Instalando Dcker
        continue-on-error: true
        run: |
          sudo curl -fsSL https://get.docker.com -o get-docker.sh && sudo sh get-docker.sh
          sudo apt install docker-compose -y

      - name: Corriendo el Bot
        timeout-minutes: 60
        continue-on-error: true
        run: |
          cd MirrorSC
          docker-compose up --build
           
      - name: Proceso de Automizacion
        timeout-minutes: 5
        continue-on-error: true
        run: |
          echo "[LOOP] Mirror USA Corriendo por 1 horas"
         
